=== JohnnyYuVe/TESINA/GameOfHistory/XML _FILE/DTD_SCHEMA/ARTICOLO_STRUTTURA.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT RECORD_ARTICOLO (ARTICOLO*)>

<!ELEMENT ARTICOLO(Nome, Prezzo, Descrizione, IMG+)>

<!ATTLIST ARTICOLO 
          ART_ID CDATA #REQUIRED>

<!ELEMENT Nome(#PCDATA)>
<!ELEMENT Prezzo(#PCDATA)>
<!ELEMENT Descrizione(#PCDATA)>

<!ELEMENT IMG(Percorso, Nome_IMG, Estensione)>
<!ELEMENT Percorso(#CDATA)>
<!ELEMENT Nome_IMG(#CDATA)>
<!ELEMENT Estensione(#CDATA)>

<!ATTLIST Estensione CDATA(jpg | png | svg | jpeg) "jpg" #REQUIRED>

=== JohnnyYuVe/TESINA/GameOfHistory/XML _FILE/XML/ARTICOLO.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE RECORD_ARTICOLO SYSTEM "http://localhost/php_program/GameOfHistory/XML%20_FILE/DTD_SCHEMA/ARTICOLO_STRUTTURA.dtd">

<RECORD_ARTICOLO>
	
				<ARTICOLO ART_ID="1">

							<Nome>God of war</Nome>
							<Prezzo>79,99</Prezzo>
							<Descrizione>Gioco bellissimo</Descrizione>

							<IMG>
								<Percorso>http://localhost/php_program/GameOfHistory/IMG_FILE/</Percorso>
								<Nome_IMG>bowling-alley-with-neon-lights</Nome_IMG>
								<Estensione>.jpg</Estensione>
							</IMG>	
				</ARTICOLO>			


</RECORD_ARTICOLO>
